type: base
build:
  auto_version: true
  variants:
    - tag: "15"
      args:
        BASE_VERSION: "15"
    - tag: "15-latest"
      args:
        BASE_VERSION: "15-latest"
    - tag: "15.1"
      args:
        BASE_VERSION: "15.1"
      aliases: ["latest", "pkg"]
    - tag: "15.1-latest"
      args:
        BASE_VERSION: "15.1-latest"
      aliases: ["pkg-latest"]

cit:
  mode: shell
