type: base
build:
  auto_version: true
  architectures:
    - amd64
    - aarch64
  variants:
    - tag: "15.1"
      args:
        BASE_VERSION: "15.1"
      aliases: ["latest", "pkg", "15"]
    - tag: "15.1-latest"
      args:
        BASE_VERSION: "15.1-latest"
      aliases: ["pkg-latest", "15-latest"]

cit:
  mode: shell
